spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://39.105.87.23:3306/redhat?serverTimezoneUTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    #切换数据源
    type: com.alibaba.druid.pool.DruidDataSource

#整合mybatis
mybatis:
    type-aliases-package: com.gao.accept_new.pojo
    mapper-locations: classpath:mybatis/mapper/*.xml
#配置静态资源路径映射
#mvc:
#  static-path-pattern: /uploads/**
#  resources:
#    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:/home/uploads/